### ISSUE TITLE
Don't need unbiasedness to reduce variance in FLAP

### ISSUE THREAD

**Issue by FinYang** [robjhyndman/subspace_projections_talk#1]
This should hold even without unbiasedness. The proof of it doesn't need unbiasedness. The unbiasedness is a nice, but separate, plus.

https://github.com/robjhyndman/subspace_projections_talk/blob/b9e1fcc5cf7ed02d757b1b119e3b82563fad5822/subspace_projections.qmd#L986-L987

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/subspace_projections_talk/commit/190f313226f466001abfd76bb829509a81636ee6
